### ISSUE TITLE
As an admin, I can define what an RFID represents.

### ISSUE THREAD

**Issue by emarchak** [myplanetdigital/galaxy-control#1]
When the endpoint receives a new RFID as POST, it queues the RFID to be categorized by a user. The RFID can represent one of two things:

A `resource`, with the following information:
- RFID (7 byte string)
- Description (long text)
- Category (short text, tags or taxonomy)

A `person`, with the following information:
- RFID (7 byte string)
- Name (long text)
- Email  (long text)

**Comment by AnastasiaD** [comment]
Done
