### ISSUE TITLE
As an admin user, I can have active endpoints.

### ISSUE THREAD

**Issue by emarchak** [myplanetdigital/galaxy-control#2]
The system contains a list of active endpoints. Use `/library/` as an example, but know that there may be more in the future. They don't have to be stored in a log or db, but need to be flexible. 

An `endpoint` contains the following information:
- Description (long text)
- Endpoint URL (short text)
- Welcome message (short text)

An endpoint can return it's the welcome message when an RFID has posted to it. 
- The displayed welcome message should be plain text, no html or encoding. 
- The endpoint has to be on `http://` _not_ `https://`.

**Comment by AnastasiaD** [comment]
Done
