### ISSUE TITLE
As a person, I can check out a resource.

### ISSUE THREAD

**Issue by emarchak** [myplanetdigital/galaxy-control#4]
If a `person` RFID taps into the `library` endpoint, they are able to checkout `resource` RFIDs. They may be able to check out multiple resources in one go. 

The steps would be as follows:
1. A `person` RFID is sent to the `library` endpoint via GET
2. The system returns the `library` welcome message with the `persons` name appended in plain text (e.g. "Welcome Anastasia") 
3. A timed session begins. 
   - If nothing is sent for the next 60 seconds, the session ends and the person must start from step one.
4. A `resource` RFID is sent to the `library` endpoint via GET. (The timed session restarts)
5. The system records the `resource` as "checked out" by the `person` at the specific time.
   - This is stored specifically against the `library` endpoint. We could have multiple endpoints on the system, remember.
6. The system returns the description of the `resource` in plain text with `Check out` prepended (e.g. "Checked out The Art of War".

If, at any point, a new `person` RFID is sent to the `library` endpoint, the old session ends and a new one begins.

**Comment by oleksii-semko** [comment]
Done
