### ISSUE TITLE
As a person, I can return a resource.

### ISSUE THREAD

**Issue by emarchak** [myplanetdigital/galaxy-control#5]
If a checked out `resource` RFID is posted to the `library` endpoint, it is flagged as returned. 

The steps would be as follows:
1. A `resource` RFID is posted to the `library` endpoint.
2. The system checks if the `resource` is recorded "checked out"
   - If it is checked out, the system records another entry marking the as "returned" 
3. The system returns the resource description, with "Returned " prepended if we've changed it's state.
   - e.g. ("The Art of War" vs. "Returned The Art of War")

**Comment by oleksii-semko** [comment]
Done
