### ISSUE TITLE
As an admin user, I can fetch a JSON that summarizes the status of an endpoint.

### ISSUE THREAD

**Issue by emarchak** [myplanetdigital/galaxy-control#6]
If someone sends a request to an endpoints url with `status` appended (e.g. `/library/status`) they receive a json summary of the end point. 

For example, the `library` endpoint would return the status of each individual book, when it was last returned (or checked out) and by who.

There may be more than one endpoint in this system, so this should be extensible.

**Comment by AnastasiaD** [comment]
Done for library endpoint. Can't be implemented for other endpoints without information about its data, schema and summary info.
